# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: redcarpet
# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "footnotes","space_after_headers","highlight","underline","quote","lax_spacing"]
# Feed!

highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: "月光林地"
description: "Do one thing, and do it well."
meta_description: 月杪的个人博客
meta_keywords: moonagic, 月杪, 月光林地, jekyll, blog, 博客, 独立博客, github
url: "https://moonagic.com"

short_url: 'moonagic.com'
google_analytics: 'UA-126239702-1'
google_analytics_url: 'https://cdn.agic.io'
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'
cdnurl: 'https://cdn.agic.io/'
# host: 0.0.0.0
# port: 4000

# Permalinks
permalink: /:title/
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate, rouge, jekyll-sitemap, jekyll-mermaid]

# mermaid
mermaid:
  src: '/assets/js/mermaid.min.js'

excerpt_separator:  '<!-- more -->'

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]
