
# Basic site information.
# TODO: You can change it to your information.

name: 月光林地
description: Do one thing, and do it well.
meta_description: 月杪的个人博客
url: "https://moonagic.com"

logo: /images/avatar.jpg
navigation: true
paginate: 10
cover: /images/cover.jpg


# Less important changes below. (Code-highlighting, markdown)

highlighter: rouge
markdown: Redcarpet
permalink: /:title/

# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "footnotes","space_after_headers","highlight","underline","quote","lax_spacing"]
# Feed!

feed:
  path: feed.xml


# However, pagination is important.

gems: [jekyll-paginate, rouge, jekyll-sitemap, jekyll-mermaid]

# mermaid
mermaid:
  src: '/assets/js/mermaid.min.js'

# This is for author page generation.

collections:
  authors: {output: true, permalink: '/authors/:path/'}
defaults:
- scope: {path: '', type: authors}
  values: {layout: author}


excerpt_separator: <!--more-->
